services:
  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:8080"
    restart: always
    environment:
      PORT: ${API_GATEWAY_PORT}
      USER_SERVICE_URL: http://user-service:8081
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_TTL_MINUTES: ${JWT_TTL_MINUTES}
    depends_on:
      - user-service
    networks:
      - ecommerce-network
    secrets:
      - jwt_private_key
      - jwt_public_key

  user-service:
    container_name: user-service
    hostname: user-service
    build:
      context: .
      dockerfile: user-service/Dockerfile
    restart: always
    environment:
      PORT: ${USER_SERVICE_PORT}
      DATABASE_URL: postgres://${USER_POSTGRES_USER}:${USER_POSTGRES_PASSWORD}@user-db:5432/${USER_POSTGRES_DB}?sslmode=disable
      MIGRATIONS_DIR: /migrations
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  product-service:
    container_name: product-service
    hostname: product-service
    build:
      context: .
      dockerfile: product-service/Dockerfile
    restart: always
    environment:
      PORT: ${PRODUCT_SERVICE_PORT}
      DATABASE_URL: postgres://${PRODUCT_POSTGRES_USER}:${PRODUCT_POSTGRES_PASSWORD}@product-db:5432/${PRODUCT_POSTGRES_DB}?sslmode=disable
      MIGRATIONS_DIR: /migrations
    depends_on:
      product-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  user-db:
    image: postgres:18-alpine
    container_name: user-db
    hostname: user-db
    restart: always
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB}
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_POSTGRES_USER} -d ${USER_POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  product-db:
    image: postgres:18-alpine
    container_name: product-db
    hostname: product-db
    restart: always
    environment:
      POSTGRES_DB: ${PRODUCT_POSTGRES_DB}
      POSTGRES_USER: ${PRODUCT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRODUCT_POSTGRES_PASSWORD}
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PRODUCT_POSTGRES_USER} -d ${PRODUCT_POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  ecommerce-network:
    driver: bridge

volumes:
  user_db_data:
  product_db_data:

secrets:
  jwt_private_key:
    file: ./certs/private.pem
  jwt_public_key:
    file: ./certs/public.pem
