// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID        pgtype.UUID        `json:"id"`
	OrderID   pgtype.UUID        `json:"orderId"`
	UserID    pgtype.UUID        `json:"userId"`
	Amount    pgtype.Numeric     `json:"amount"`
	Status    pgtype.UUID        `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type PaymentStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
