// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, user_id, amount)
VALUES ($1, $2, $3)
RETURNING id, order_id, user_id, amount, status, created_at
`

type CreatePaymentParams struct {
	OrderID pgtype.UUID    `json:"orderId"`
	UserID  pgtype.UUID    `json:"userId"`
	Amount  pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment, arg.OrderID, arg.UserID, arg.Amount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, user_id, amount, status, created_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentStatusByName = `-- name: GetPaymentStatusByName :one
SELECT id FROM payment_statuses
WHERE name = $1
`

func (q *Queries) GetPaymentStatusByName(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPaymentStatusByName, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2
WHERE id = $1
RETURNING id, order_id, user_id, amount, status, created_at
`

type UpdatePaymentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.UUID `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
