// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEventStatus string

const (
	OutboxEventStatusUNPUBLISHED OutboxEventStatus = "UNPUBLISHED"
	OutboxEventStatusPUBLISHED   OutboxEventStatus = "PUBLISHED"
	OutboxEventStatusCANCELLED   OutboxEventStatus = "CANCELLED"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outboxEventStatus"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"userId"`
	TotalAmount pgtype.Numeric     `json:"totalAmount"`
	Status      pgtype.UUID        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type OrderStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type OutboxEvent struct {
	ID          pgtype.UUID        `json:"id"`
	AggregateID pgtype.UUID        `json:"aggregateId"`
	EventName   string             `json:"eventName"`
	Payload     []byte             `json:"payload"`
	Status      OutboxEventStatus  `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	PublishedAt pgtype.Timestamptz `json:"publishedAt"`
}
