// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"userId"`
	TotalAmount pgtype.Numeric     `json:"totalAmount"`
	Status      pgtype.UUID        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type OrderStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type OutboxEvent struct {
	ID          pgtype.UUID        `json:"id"`
	AggregateID pgtype.UUID        `json:"aggregateId"`
	EventName   string             `json:"eventName"`
	Payload     []byte             `json:"payload"`
	Status      interface{}        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	PublishedAt pgtype.Timestamptz `json:"publishedAt"`
}
