// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, total_amount)
VALUES ($1, $2)
RETURNING id, user_id, total_amount, status, created_at
`

type CreateOrderParams struct {
	UserID      pgtype.UUID    `json:"userId"`
	TotalAmount pgtype.Numeric `json:"totalAmount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TotalAmount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderStatusIDByName = `-- name: GetOrderStatusIDByName :one
SELECT id
FROM order_statuses
WHERE name = $1
`

func (q *Queries) GetOrderStatusIDByName(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrderStatusIDByName, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2
WHERE id = $1
RETURNING id, user_id, total_amount, status, created_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.UUID `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
