// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox_event.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (aggregate_id, event_name, payload)
VALUES ($1, $2, $3)
`

type CreateOutboxEventParams struct {
	AggregateID pgtype.UUID `json:"aggregateId"`
	EventName   string      `json:"eventName"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent, arg.AggregateID, arg.EventName, arg.Payload)
	return err
}

const getUnpublishedOutboxEvents = `-- name: GetUnpublishedOutboxEvents :many
SELECT id, aggregate_id, event_name, payload, status, created_at, published_at
FROM outbox_events
WHERE status = 'UNPUBLISHED'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventName,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutboxEventStatus = `-- name: UpdateOutboxEventStatus :exec
UPDATE outbox_events
SET
    status = $2,
    published_at = NOW()
WHERE
    id = $1
`

type UpdateOutboxEventStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status interface{} `json:"status"`
}

func (q *Queries) UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateOutboxEventStatus, arg.ID, arg.Status)
	return err
}
