// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	GetOrderStatusByName(ctx context.Context, name string) (GetOrderStatusByNameRow, error)
	GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOutboxEventStatus(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
