// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Code          string             `json:"code"`
	Price         pgtype.Numeric     `json:"price"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StockQuantity int32              `json:"stock_quantity"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
