// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID          pgtype.UUID        `json:"id"`
	AggregateID pgtype.UUID        `json:"aggregateId"`
	EventName   string             `json:"eventName"`
	Payload     []byte             `json:"payload"`
	Status      interface{}        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	PublishedAt pgtype.Timestamptz `json:"publishedAt"`
}

type ProcessedEvent struct {
	ID          pgtype.UUID        `json:"id"`
	AggregateID pgtype.UUID        `json:"aggregateId"`
	EventName   string             `json:"eventName"`
	ProcessedAt pgtype.Timestamptz `json:"processedAt"`
}

type Product struct {
	ID            pgtype.UUID        `json:"id"`
	CategoryID    pgtype.UUID        `json:"categoryId"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Price         pgtype.Numeric     `json:"price"`
	StockQuantity int32              `json:"stockQuantity"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type ProductCategory struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}
