// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID            pgtype.UUID        `json:"id"`
	CategoryID    pgtype.UUID        `json:"categoryId"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Price         pgtype.Numeric     `json:"price"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	StockQuantity int32              `json:"stockQuantity"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type ProductCategory struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}
