// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: processed_events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProcessedEvent = `-- name: CreateProcessedEvent :exec
INSERT INTO processed_events (aggregate_id, event_name)
VALUES ($1, $2)
`

type CreateProcessedEventParams struct {
	AggregateID pgtype.UUID `json:"aggregateId"`
	EventName   string      `json:"eventName"`
}

func (q *Queries) CreateProcessedEvent(ctx context.Context, arg CreateProcessedEventParams) error {
	_, err := q.db.Exec(ctx, createProcessedEvent, arg.AggregateID, arg.EventName)
	return err
}

const getProcessedEventByAggregateIDAndEventName = `-- name: GetProcessedEventByAggregateIDAndEventName :one
SELECT id, aggregate_id, event_name, processed_at FROM processed_events
WHERE aggregate_id = $1 AND event_name = $2
`

type GetProcessedEventByAggregateIDAndEventNameParams struct {
	AggregateID pgtype.UUID `json:"aggregateId"`
	EventName   string      `json:"eventName"`
}

func (q *Queries) GetProcessedEventByAggregateIDAndEventName(ctx context.Context, arg GetProcessedEventByAggregateIDAndEventNameParams) (ProcessedEvent, error) {
	row := q.db.QueryRow(ctx, getProcessedEventByAggregateIDAndEventName, arg.AggregateID, arg.EventName)
	var i ProcessedEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.EventName,
		&i.ProcessedAt,
	)
	return i, err
}
