// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  category_id,
  name,
  description,
  price,
  stock_quantity
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, category_id, name, description, price, created_at, stock_quantity, updated_at
`

type CreateProductParams struct {
	CategoryID    pgtype.UUID    `json:"categoryId"`
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stockQuantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.StockQuantity,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, category_id, name, description, price, created_at, stock_quantity, updated_at FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.StockQuantity,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductsByCategoryID = `-- name: GetProductsByCategoryID :many
SELECT id, category_id, name, description, price, created_at, stock_quantity, updated_at FROM products
WHERE category_id = $1
ORDER BY id
`

func (q *Queries) GetProductsByCategoryID(ctx context.Context, categoryID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.StockQuantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByIDs = `-- name: GetProductsByIDs :many
SELECT id, category_id, name, description, price, created_at, stock_quantity, updated_at FROM products
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetProductsByIDs(ctx context.Context, productIds []pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByIDs, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.StockQuantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPaginated = `-- name: ListProductsPaginated :many
SELECT id, category_id, name, description, price, created_at, stock_quantity, updated_at FROM products
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListProductsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProductsPaginated(ctx context.Context, arg ListProductsPaginatedParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.StockQuantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
  category_id = $2,
  name = $3,
  description = $4,
  price = $5,
  stock_quantity = $6,
  updated_at = NOW()
WHERE id = $1
RETURNING id, category_id, name, description, price, created_at, stock_quantity, updated_at
`

type UpdateProductParams struct {
	ID            pgtype.UUID    `json:"id"`
	CategoryID    pgtype.UUID    `json:"categoryId"`
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stockQuantity"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.StockQuantity,
		&i.UpdatedAt,
	)
	return i, err
}
