// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteProductCategory(ctx context.Context, id pgtype.UUID) error
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductCategories(ctx context.Context) ([]ProductCategory, error)
	GetProductsByCategoryID(ctx context.Context, categoryID pgtype.UUID) ([]Product, error)
	GetProductsByIDs(ctx context.Context, productIds []pgtype.UUID) ([]Product, error)
	ListProductsPaginated(ctx context.Context, arg ListProductsPaginatedParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) error
	UpdateStockBatch(ctx context.Context, updateParams []byte) (int64, error)
}

var _ Querier = (*Queries)(nil)
