// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type CartsProduct struct {
	ID        pgtype.UUID        `json:"id"`
	CartID    pgtype.UUID        `json:"cartId"`
	ProductID pgtype.UUID        `json:"productId"`
	Quantity  int32              `json:"quantity"`
	Price     pgtype.Numeric     `json:"price"`
	AddedAt   pgtype.Timestamptz `json:"addedAt"`
}
