// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrUpdateProductInCart(ctx context.Context, arg AddOrUpdateProductInCartParams) (CartsProduct, error)
	ClearCartProductsByUserID(ctx context.Context, userID pgtype.UUID) error
	CreateCart(ctx context.Context, userID pgtype.UUID) (Cart, error)
	DeleteCartByUserID(ctx context.Context, userID pgtype.UUID) error
	GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error)
	GetCartProductsByCartID(ctx context.Context, cartID pgtype.UUID) ([]GetCartProductsByCartIDRow, error)
	RemoveProductFromCart(ctx context.Context, arg RemoveProductFromCartParams) error
}

var _ Querier = (*Queries)(nil)
