// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCart(ctx context.Context, userID pgtype.UUID) (Cart, error)
	DeleteCartByUserID(ctx context.Context, userID pgtype.UUID) error
	GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error)
	GetCartProductsByCartID(ctx context.Context, cartID pgtype.UUID) ([]GetCartProductsByCartIDRow, error)
}

var _ Querier = (*Queries)(nil)
